#server:
#  applicationConnectors:
#    - type: http
#      port: 8090
#  adminConnectors:
#    - type: http
#      port: 8091

database:
  driverClass:  com.mysql.jdbc.Driver
  user:   root
  password: 123456
  url:  jdbc:mysql://localhost:3306/project1
  properties:
      charSet: UTF-8
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.auto: update